version: "3.8"
services:
    # image project
    curso_api_cache:
        build: 
            args: 
                user: alisson
                uid: 1000
            context: ./
            dockerfile: ./docker/curso_api_cache/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - cursoapicache
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8989:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - cursoapicache

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - cursoapicache

    # queue
    queue:
        build: 
            args: 
                user: alisson
                uid: 1000
            context: ./
            dockerfile: ./docker/queue/Dockerfile
        image: queue
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - cursoapicache

    # redis
    redis:
        image: redis:latest
        networks: 
            - cursoapicache

networks: 
    cursoapicache:
        driver: bridge